name: CI with ngrok

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      # Build the application
      - name: Build with Maven
        run: ./mvnw clean install

      # Run the application
      - name: Start the Spring Boot application
        run: nohup ./mvnw spring-boot:run &

      # Install and set up ngrok
      - name: Install ngrok
        run: |
          sudo apt-get install -y unzip
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update
          sudo apt-get install ngrok

      - name: Expose app with ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          ngrok config add-authtoken $NGROK_AUTH_TOKEN
          nohup ngrok http 8080 &
          sleep 10
          curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'

      # Output ngrok URL
      - name: Print ngrok URL
        run: curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
